name: Build

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install CURL
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Install OpenSSL
        run: sudo apt-get install libssl-dev
      - name: Install ZLIB  (for libcurl)
        run: sudo apt-get install zlib1g-dev

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --verbose

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: choco install -y mingw

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -G "MinGW Makefiles" ..
          cmake --build . --verbose

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_CXX_COMPILER=$(brew --prefix llvm@15)/bin/clang++  ..
          cmake --build . --verbose
